### ISSUE TITLE
Erro no R

### ISSUE THREAD

**Issue by CarllaAmara** [nextmarte/dataVizR3#15]
Marcus, boa tarde!
Estou tentando fazer o exercício. Fiz a parte 1, mas quando vou pro deploy o R da o seguinte erro:

Quitting from lines 70-78 (Likert5.qmd)
Error in contrib.url(repos, "source") :
  trying to use CRAN without setting a mirror
Calls: .main ... eval_with_user_handlers -> eval -> eval -> install.packages -> contrib.url
Execu��o interrompida
R scripting front-end version 4.1.0 (2021-05-18)
Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/

Sabe me dizer como faço para corrigir? Seria atualizando o R?
Obrigada
Carlla

**Comment by nextmarte** [comment]
@CarllaAmara Você precisa instalar o R. baixe a versão mais recente do R no link [CLICA AQUI!!!](https://cloud.r-project.org/)

**Comment by CarllaAmara** [comment]
Imaginei isso. Vou testar e qq dificuldade te falo. Obrigada!

**Comment by nextmarte** [comment]
Perfeito, voun deixar a issue aberta por enquanto até você conseguir entregar.

**Comment by CarllaAmara** [comment]
Marcus, segui sua orientação e reinstalei o R.
Uma dúvida: essa tarefa pode ser em grupo ou é individual?

**Comment by nextmarte** [comment]
Individual, mas vcs podem se ajudar é claro. O dashboard q era em grupo.

**Comment by CarllaAmara** [comment]
![erro au fazer o push](https://github.com/nextmarte/dataVizR3/assets/157220298/cb451607-367f-4e2a-9e66-ede16dc7135b)

Marcus, consegui fazer o pull, mas qdo fui fazer  o Create pull request deu esse erro.
Obrigada

**Comment by CarllaAmara** [comment]
Acho que foi pq não alterei pra branch main

**Comment by CarllaAmara** [comment]
Consigo retornar apenas do passo anterior ao push ou preciso fazer tudo novamente?

**Comment by nextmarte** [comment]
@CarllaAmara tava tudo certo, a mensagem em vermelho aparece porque eu preciso aprova o seu pull request.

**Comment by nextmarte** [comment]
Pode refazer o pull request

**Comment by CarllaAmara** [comment]
Obrigada! Tentei, mas acho que não funcionou, pois não apareceu a opção do pull aqui no git
![image](https://github.com/nextmarte/dataVizR3/assets/157220298/13b30099-41fc-4a1a-9914-3d3664666c64)

Além disso, meu grupo perguntou se pode ser um dash em shiny, dando up de uma pasta?

Obrigada mais uma vez.

**Comment by nextmarte** [comment]
Individual, mas vcs podem se ajudar é claro. O dashboard q era em grupo.

Pode sim

**Comment by nextmarte** [comment]
> Obrigada! Tentei, mas acho que não funcionou, pois não apareceu a opção do pull aqui no git
> ![image](https://github.com/nextmarte/dataVizR3/assets/157220298/13b30099-41fc-4a1a-9914-3d3664666c64)
> 
> Além disso, meu grupo perguntou se pode ser um dash em shiny, dando up de uma pasta?
> 
> Obrigada mais uma vez.

Pode sim
