### ISSUE TITLE
Nao consigo adicionar os arquivos na pasta de tarefas

### ISSUE THREAD

**Issue by gustavobgiusti** [nextmarte/dataVizR3#8]
Olá, já fiz tudo certinho seguindo o roteiro passado, mas quando chega para adicionar os arquivos, ele não aparece depois para meu github, poderia detalhar melhor com
![image](https://github.com/nextmarte/dataVizR3/assets/47858935/0aadc064-92f2-48f3-a8ef-8d1bc053d146)
o eu posso fazer isso? Eu criei uma pasta com meu nome dentro do Tarefas e criei o arquivo MD

![image](https://github.com/nextmarte/dataVizR3/assets/47858935/a540fda8-5032-4d78-b6e2-b5f38e6f6f4c)

**Comment by gustavobgiusti** [comment]
Tentei hoje de novo e ocorreu esse erro:

![image](https://github.com/nextmarte/dataVizR3/assets/47858935/34d3c856-81c3-49cf-9568-3e827d274e90)

**Comment by nextmarte** [comment]
Gistavo, sempre que for fazer um commit e um push pra um branch, você precisa verificar antes se exsitem updates para serem baixados usando o git pull, desde a aula, outros alunos entregaram a tarefa, então repositório foi atualizado.

Tente novamente seguindo os passos abaixo:

1- Faça o fork do repositório da aula
2 - Adicione o repositório original da aula ao remote upstram para poder baixar sempre que possível as ultimas atualizações usando `git remote add upstream https://github.com/nextmarte/dataVizR3.git`
2 - Crie um branch com seu nome 
3 - adicione a pasta com seu trabalho conforme explicado em aula dentro da pasta tarefas
4 - adicione o link para o seu dashboard online ou para o repositório do mesmo no README.md na pasta raiz da aula
5 - Faça um git add . , um git commit -m mensagem e um git push
6 - Vá até o github e solicite o pull request
